/**
 * Realistic demo dataset for investor demos and product walkthroughs.
 * Set NEXT_PUBLIC_USE_DEMO_DATA=false to return empty API responses (integration testing).
 */
import type {
  AIModel,
  AutonomyConfig,
  Benchmark,
  BrandProfile,
  ChannelConfig,
  CostBreakdown,
  CreditPack,
  Deliverable,
  ExpertAssignment,
  FeedbackTranslation,
  Invoice,
  Lead,
  PerformanceMetric,
  Pipeline,
  AITask,
  ProactiveSuggestion,
  PublishingJob,
  Project,
  RevenueMetric,
  Review,
  SLACompliance,
  SLATier,
  UsageRecord,
} from "@/types"

const iso = (d: string) => new Date(d).toISOString()

export const demoProjects: Project[] = [
  {
    id: "proj_lumen",
    title: "Lumen Analytics — full rebrand",
    type: "brand_identity",
    status: "client_review",
    priority: "high",
    clientId: "c_lumen",
    clientName: "Lumen Analytics",
    expertId: "exp_maya",
    estimatedCost: 18500,
    actualCost: 16200,
    aiCost: 4200,
    confidenceScore: 0.91,
    autonomyLevel: "spot_check",
    qualityScore: 8.7,
    dueDate: iso("2026-04-28"),
    createdAt: iso("2026-03-12"),
    updatedAt: iso("2026-04-10"),
    deliverableCount: 4,
    revisionCount: 1,
  },
  {
    id: "proj_pulse",
    title: "Pulse Health — Q2 social motion kit",
    type: "social_media",
    status: "expert_review",
    priority: "urgent",
    clientId: "c_pulse",
    clientName: "Pulse Health",
    expertId: "exp_jordan",
    estimatedCost: 12400,
    actualCost: 9800,
    aiCost: 5100,
    confidenceScore: 0.88,
    autonomyLevel: "autonomous",
    qualityScore: 8.2,
    dueDate: iso("2026-04-18"),
    createdAt: iso("2026-03-28"),
    updatedAt: iso("2026-04-11"),
    deliverableCount: 12,
    revisionCount: 0,
  },
  {
    id: "proj_north",
    title: "Northwind — performance creative A/B",
    type: "ad_creative",
    status: "qa_check",
    priority: "high",
    clientId: "c_north",
    clientName: "Northwind Commerce",
    estimatedCost: 8900,
    actualCost: 7200,
    aiCost: 3800,
    confidenceScore: 0.85,
    autonomyLevel: "spot_check",
    qualityScore: 8.4,
    dueDate: iso("2026-04-22"),
    createdAt: iso("2026-04-02"),
    updatedAt: iso("2026-04-09"),
    deliverableCount: 8,
    revisionCount: 2,
  },
  {
    id: "proj_vertex",
    title: "Vertex Labs — investor one-pager + deck",
    type: "marketing_collateral",
    status: "delivered",
    priority: "medium",
    clientId: "c_vertex",
    clientName: "Vertex Labs",
    estimatedCost: 6200,
    actualCost: 5800,
    aiCost: 2100,
    confidenceScore: 0.93,
    autonomyLevel: "autonomous",
    qualityScore: 9.1,
    dueDate: iso("2026-04-05"),
    createdAt: iso("2026-03-01"),
    updatedAt: iso("2026-04-04"),
    deliverableCount: 6,
    revisionCount: 0,
  },
  {
    id: "proj_apex",
    title: "Apex Freight — logo refinement",
    type: "logo_design",
    status: "ai_generating",
    priority: "medium",
    clientId: "c_apex",
    clientName: "Apex Freight",
    estimatedCost: 4500,
    actualCost: 1200,
    aiCost: 800,
    confidenceScore: 0.79,
    autonomyLevel: "human_required",
    qualityScore: 7.8,
    dueDate: iso("2026-04-30"),
    createdAt: iso("2026-04-08"),
    updatedAt: iso("2026-04-11"),
    deliverableCount: 2,
    revisionCount: 0,
  },
  {
    id: "proj_kite",
    title: "Kite Bank — lifecycle email series",
    type: "email_campaign",
    status: "draft",
    priority: "low",
    clientId: "c_kite",
    clientName: "Kite Bank",
    estimatedCost: 7200,
    actualCost: 0,
    aiCost: 0,
    confidenceScore: 0.72,
    autonomyLevel: "spot_check",
    qualityScore: 0,
    dueDate: iso("2026-05-15"),
    createdAt: iso("2026-04-10"),
    updatedAt: iso("2026-04-10"),
    deliverableCount: 0,
    revisionCount: 0,
  },
]

export const demoDeliverables: Deliverable[] = [
  {
    id: "del_lumen_1",
    projectId: "proj_lumen",
    version: 3,
    title: "Brand guidelines — digital",
    type: "PDF",
    fileUrl: "https://placehold.co/1200x800/4f46e5/ffffff/png?text=Lumen+Guidelines",
    thumbnailUrl: "https://placehold.co/400x300/4f46e5/ffffff/png?text=Guidelines",
    status: "review",
    aiModel: "claude-3.5-sonnet",
    generationCost: 42,
    generationTime: 118,
    qualityScore: 8.7,
    createdAt: iso("2026-04-09"),
  },
  {
    id: "del_pulse_1",
    projectId: "proj_pulse",
    version: 2,
    title: "IG Reels batch — week 1",
    type: "MP4 bundle",
    fileUrl: "https://placehold.co/1080x1920/0ea5e9/ffffff/png?text=Reels",
    thumbnailUrl: "https://placehold.co/400x300/0ea5e9/ffffff/png?text=Reels",
    status: "qa_check",
    aiModel: "runway-gen3",
    generationCost: 128,
    generationTime: 420,
    qualityScore: 8.2,
    createdAt: iso("2026-04-10"),
  },
  {
    id: "del_north_1",
    projectId: "proj_north",
    version: 1,
    title: "Meta carousel — variant B",
    type: "PNG set",
    fileUrl: "https://placehold.co/1080x1080/f97316/ffffff/png?text=Carousel+B",
    thumbnailUrl: "https://placehold.co/400x300/f97316/ffffff/png?text=Ads",
    status: "qa_check",
    aiModel: "flux-pro",
    generationCost: 18,
    generationTime: 64,
    qualityScore: 8.4,
    createdAt: iso("2026-04-08"),
  },
  {
    id: "del_vertex_1",
    projectId: "proj_vertex",
    version: 1,
    title: "One-pager — Series B",
    type: "PDF",
    fileUrl: "https://placehold.co/1200x800/10b981/ffffff/png?text=One-pager",
    thumbnailUrl: "https://placehold.co/400x300/10b981/ffffff/png?text=PDF",
    status: "approved",
    aiModel: "claude-3.5-sonnet",
    generationCost: 22,
    generationTime: 95,
    qualityScore: 9.1,
    createdAt: iso("2026-04-03"),
  },
]

const comment = (
  id: string,
  author: string,
  role: "admin" | "expert" | "client",
  content: string,
  createdAt: string,
): Review["comments"][0] => ({
  id,
  author,
  authorRole: role,
  content,
  createdAt: iso(createdAt),
})

export const demoReviews: Review[] = [
  {
    id: "rev_lumen",
    deliverableId: "del_lumen_1",
    projectId: "proj_lumen",
    reviewerId: "u_client_lumen",
    reviewerName: "Sarah Chen",
    reviewerRole: "client",
    status: "revision_requested",
    rating: 4,
    comments: [
      comment("cm1", "Sarah Chen", "client", "Love the palette shift. Can we tighten typography scale on slide 4?", "2026-04-10"),
      comment("cm2", "Maya Okonkwo", "expert", "Captured — regenerating headings with tighter scale tokens.", "2026-04-10"),
    ],
    timeSpent: 18,
    createdAt: iso("2026-04-10"),
  },
  {
    id: "rev_pulse",
    deliverableId: "del_pulse_1",
    projectId: "proj_pulse",
    reviewerId: "exp_jordan",
    reviewerName: "Jordan Lee",
    reviewerRole: "expert",
    status: "pending",
    rating: 0,
    comments: [],
    timeSpent: 0,
    createdAt: iso("2026-04-11"),
  },
  {
    id: "rev_vertex",
    deliverableId: "del_vertex_1",
    projectId: "proj_vertex",
    reviewerId: "exp_maya",
    reviewerName: "Maya Okonkwo",
    reviewerRole: "expert",
    status: "approved",
    rating: 5,
    comments: [
      comment("cm3", "Maya Okonkwo", "expert", "Clean narrative arc; numbers footnotes verified against data room.", "2026-04-04"),
    ],
    timeSpent: 24,
    createdAt: iso("2026-04-04"),
  },
]

export const demoExpertAssignments: ExpertAssignment[] = [
  {
    id: "ea_1",
    projectId: "proj_pulse",
    projectTitle: "Pulse Health — Q2 social motion kit",
    projectType: "social_media",
    expertId: "exp_jordan",
    expertName: "Jordan Lee",
    status: "in_review",
    escalationLevel: "standard",
    priority: "urgent",
    claimedAt: iso("2026-04-11T09:00:00"),
    reviewTimeMinutes: 42,
    qualityBefore: 7.9,
    qualityAfter: 8.2,
  },
  {
    id: "ea_2",
    projectId: "proj_lumen",
    projectTitle: "Lumen Analytics — full rebrand",
    projectType: "brand_identity",
    expertId: "exp_maya",
    expertName: "Maya Okonkwo",
    status: "claimed",
    escalationLevel: "senior",
    priority: "high",
    claimedAt: iso("2026-04-10T14:20:00"),
    reviewTimeMinutes: 55,
    qualityBefore: 8.4,
    qualityAfter: 8.7,
  },
  {
    id: "ea_3",
    projectId: "proj_north",
    projectTitle: "Northwind — performance creative A/B",
    projectType: "ad_creative",
    expertId: "exp_jordan",
    expertName: "Jordan Lee",
    status: "queued",
    escalationLevel: "standard",
    priority: "high",
    reviewTimeMinutes: 0,
    qualityBefore: 8.0,
    qualityAfter: 8.0,
  },
]

export const demoRevenueMetrics: RevenueMetric[] = [
  { month: "2025-11", revenue: 118000, cost: 42000, profit: 76000, margin: 0.644, projects: 14, clients: 9 },
  { month: "2025-12", revenue: 132000, cost: 46000, profit: 86000, margin: 0.652, projects: 16, clients: 10 },
  { month: "2026-01", revenue: 141000, cost: 51000, profit: 90000, margin: 0.638, projects: 17, clients: 11 },
  { month: "2026-02", revenue: 156000, cost: 54000, profit: 102000, margin: 0.654, projects: 19, clients: 12 },
  { month: "2026-03", revenue: 168000, cost: 58000, profit: 110000, margin: 0.655, projects: 21, clients: 13 },
  { month: "2026-04", revenue: 142000, cost: 48000, profit: 94000, margin: 0.662, projects: 18, clients: 12 },
]

export const demoCostBreakdown: CostBreakdown[] = [
  { category: "LLM routing & prompts", amount: 18400, percentage: 38, trend: "up" },
  { category: "Image & video generation", amount: 15200, percentage: 32, trend: "stable" },
  { category: "Expert review time", amount: 9800, percentage: 20, trend: "down" },
  { category: "Embeddings & retrieval", amount: 4800, percentage: 10, trend: "stable" },
]

export const demoLeads: Lead[] = [
  {
    id: "lead_1",
    company: "Harbor Robotics",
    contactName: "Elena Voss",
    email: "elena@harborrobotics.io",
    status: "demo_scheduled",
    value: 84000,
    source: "Outbound — design partner",
    notes: "Series A; wants creative ops on retainer.",
    createdAt: iso("2026-04-01"),
    lastContactAt: iso("2026-04-09"),
    nextFollowUp: iso("2026-04-14"),
  },
  {
    id: "lead_2",
    company: "Cedar Bio",
    contactName: "Dev Shah",
    email: "dev@cedarbio.com",
    status: "proposal_sent",
    value: 52000,
    source: "Referral — Lumen",
    notes: "Comparing against traditional agency quote.",
    createdAt: iso("2026-03-20"),
    lastContactAt: iso("2026-04-08"),
  },
  {
    id: "lead_3",
    company: "SignalForge",
    contactName: "Priya Nand",
    email: "priya@signalforge.ai",
    phone: "+1 415 555 0192",
    status: "negotiating",
    value: 120000,
    source: "Conference — SaaStr",
    notes: "Enterprise security review in progress.",
    createdAt: iso("2026-02-14"),
    lastContactAt: iso("2026-04-10"),
  },
  {
    id: "lead_4",
    company: "Bluecart",
    contactName: "Marcus Hill",
    email: "marcus@bluecart.shop",
    status: "new",
    value: 28000,
    source: "Inbound — website",
    notes: "Asked about SLA tiers.",
    createdAt: iso("2026-04-11"),
    lastContactAt: iso("2026-04-11"),
  },
]

function task(
  partial: Omit<AITask, "id" | "pipelineId" | "createdAt"> & { id: string },
  pipelineId: string,
): AITask {
  return {
    ...partial,
    pipelineId,
    createdAt: iso("2026-04-11T10:00:00"),
  }
}

export const demoPipelines: Pipeline[] = [
  {
    id: "pipe_pulse_live",
    projectId: "proj_pulse",
    projectTitle: "Pulse Health — Q2 social motion kit",
    status: "running",
    totalCost: 127.84,
    totalTime: 184,
    startedAt: iso("2026-04-11T10:02:00"),
    tasks: [
      task(
        {
          id: "t1",
          type: "brief_analysis",
          modelId: "mdl_claude",
          modelName: "Claude 3.5 Sonnet",
          status: "completed",
          input: "Brief + brand DNA",
          output: "Structured creative brief",
          cost: 0.42,
          latencyMs: 4200,
          retryCount: 0,
          completedAt: iso("2026-04-11T10:03:00"),
        },
        "pipe_pulse_live",
      ),
      task(
        {
          id: "t2",
          type: "storyboard_image",
          modelId: "mdl_flux",
          modelName: "FLUX Pro",
          status: "completed",
          input: "Key frames x6",
          cost: 18.2,
          latencyMs: 28000,
          retryCount: 0,
          completedAt: iso("2026-04-11T10:08:00"),
        },
        "pipe_pulse_live",
      ),
      task(
        {
          id: "t3",
          type: "video_generation",
          modelId: "mdl_runway",
          modelName: "Runway Gen-3",
          status: "running",
          input: "Motion from frames",
          cost: 89.5,
          latencyMs: 0,
          retryCount: 0,
        },
        "pipe_pulse_live",
      ),
      task(
        {
          id: "t4",
          type: "qa_validation",
          modelId: "mdl_claude",
          modelName: "Claude 3.5 Sonnet",
          status: "queued",
          input: "QC checklist",
          cost: 0,
          latencyMs: 0,
          retryCount: 0,
        },
        "pipe_pulse_live",
      ),
    ],
  },
  {
    id: "pipe_lumen_done",
    projectId: "proj_lumen",
    projectTitle: "Lumen Analytics — full rebrand",
    status: "completed",
    totalCost: 64.12,
    totalTime: 96,
    startedAt: iso("2026-04-09T08:00:00"),
    completedAt: iso("2026-04-09T09:36:00"),
    tasks: [
      task(
        {
          id: "t5",
          type: "strategy",
          modelId: "mdl_claude",
          modelName: "Claude 3.5 Sonnet",
          status: "completed",
          input: "Positioning workshop notes",
          cost: 1.1,
          latencyMs: 9100,
          retryCount: 0,
          completedAt: iso("2026-04-09T08:05:00"),
        },
        "pipe_lumen_done",
      ),
      task(
        {
          id: "t6",
          type: "design_system",
          modelId: "mdl_flux",
          modelName: "FLUX Pro",
          status: "completed",
          input: "Tokens + components",
          cost: 22.4,
          latencyMs: 45000,
          retryCount: 0,
          completedAt: iso("2026-04-09T08:25:00"),
        },
        "pipe_lumen_done",
      ),
      task(
        {
          id: "t7",
          type: "copy_generation",
          modelId: "mdl_claude",
          modelName: "Claude 3.5 Sonnet",
          status: "completed",
          input: "Voice guidelines",
          cost: 0.62,
          latencyMs: 6800,
          retryCount: 0,
          completedAt: iso("2026-04-09T08:40:00"),
        },
        "pipe_lumen_done",
      ),
    ],
  },
]

export const demoAIModels: AIModel[] = [
  {
    id: "mdl_claude",
    provider: "anthropic",
    name: "Claude 3.5 Sonnet",
    capabilities: ["reasoning", "long_context", "tool_use"],
    costPer1kTokens: 0.003,
    avgLatencyMs: 8200,
    qualityScore: 9.2,
    isActive: true,
  },
  {
    id: "mdl_gpt4",
    provider: "openai",
    name: "GPT-4o",
    capabilities: ["multimodal", "fast"],
    costPer1kTokens: 0.005,
    avgLatencyMs: 4100,
    qualityScore: 8.9,
    isActive: true,
  },
  {
    id: "mdl_flux",
    provider: "replicate",
    name: "FLUX Pro",
    capabilities: ["image", "high_res"],
    costPer1kTokens: 0,
    avgLatencyMs: 22000,
    qualityScore: 9.0,
    isActive: true,
  },
  {
    id: "mdl_runway",
    provider: "runway",
    name: "Runway Gen-3",
    capabilities: ["video"],
    costPer1kTokens: 0,
    avgLatencyMs: 120000,
    qualityScore: 8.6,
    isActive: true,
  },
]

export const demoAutonomyConfigs: AutonomyConfig[] = [
  {
    id: "auto_sm",
    taskType: "social_media",
    taskLabel: "Social & motion kits",
    currentLevel: "autonomous",
    confidenceScore: 0.88,
    totalCompleted: 142,
    successRate: 0.94,
    revisionRate: 0.08,
    avgQualityScore: 8.3,
    trend: "improving",
    projectedAutonomyDate: iso("2026-06-01"),
  },
  {
    id: "auto_brand",
    taskType: "brand_identity",
    taskLabel: "Brand & guidelines",
    currentLevel: "spot_check",
    confidenceScore: 0.81,
    totalCompleted: 58,
    successRate: 0.89,
    revisionRate: 0.14,
    avgQualityScore: 8.6,
    trend: "stable",
  },
  {
    id: "auto_logo",
    taskType: "logo_design",
    taskLabel: "Logo & marks",
    currentLevel: "human_required",
    confidenceScore: 0.68,
    totalCompleted: 31,
    successRate: 0.82,
    revisionRate: 0.22,
    avgQualityScore: 8.1,
    trend: "improving",
  },
]

export const demoPerformanceMetrics: PerformanceMetric[] = [
  {
    id: "pm1",
    deliverableId: "del_north_1",
    projectTitle: "Northwind — carousel B",
    channel: "meta_ads",
    impressions: 428000,
    clicks: 12650,
    ctr: 0.0295,
    conversions: 184,
    spend: 6200,
    roi: 3.8,
    measuredAt: iso("2026-04-09"),
  },
  {
    id: "pm2",
    deliverableId: "del_pulse_1",
    projectTitle: "Pulse — reels batch",
    channel: "instagram",
    impressions: 890000,
    clicks: 24100,
    ctr: 0.0271,
    conversions: 402,
    spend: 4100,
    roi: 5.1,
    measuredAt: iso("2026-04-08"),
  },
]

export const demoSuggestions: ProactiveSuggestion[] = [
  {
    id: "sug1",
    tenantId: "t_demo",
    clientName: "Lumen Analytics",
    type: "social_media",
    title: "Launch thought-leadership clips from Q1 benchmark report",
    description: "Repurpose the data narrative into 5 short clips while search volume on “AI analytics” is up 22%.",
    reasoning: "Trend spike + unused hero asset from last deliverable.",
    trendSource: "Google Trends · category: analytics",
    relevanceScore: 0.91,
    estimatedValue: 18000,
    status: "pending",
    createdAt: iso("2026-04-10"),
    expiresAt: iso("2026-04-24"),
  },
  {
    id: "sug2",
    tenantId: "t_demo",
    clientName: "Northwind Commerce",
    type: "ad_creative",
    title: "Expand winning carousel into YouTube Shorts",
    description: "Top quartile CTR; Shorts CPMs down 11% WoW in their vertical.",
    reasoning: "Performance gap vs. industry benchmark on YT.",
    trendSource: "Internal benchmarks + channel pricing",
    relevanceScore: 0.84,
    estimatedValue: 9600,
    status: "generated",
    createdAt: iso("2026-04-07"),
    expiresAt: iso("2026-04-21"),
  },
]

export const demoFeedbackTranslations: FeedbackTranslation[] = [
  {
    id: "ft1",
    original: "It feels a bit too playful for our compliance story — can we dial back the illustration style?",
    translated: "Reduce illustration weight; shift visual tone toward enterprise trust signals (reference: pages 2–4 of brand guidelines).",
    confidence: 0.93,
    category: "aesthetic",
    actionableItems: [
      { action: "adjust", parameter: "illustration_density", value: "low", priority: "high" },
      { action: "emphasize", parameter: "trust_markers", value: "logos + certifications strip", priority: "medium" },
    ],
  },
  {
    id: "ft2",
    original: "The headline is catchy but I worry it overpromises on ROI.",
    translated: "Soften performance claim in H1; align copy to verified metrics in appendix C.",
    confidence: 0.89,
    category: "content",
    actionableItems: [
      { action: "replace", parameter: "hero_headline", value: "Outcome-led, qualified headline", priority: "high" },
    ],
  },
]

export const demoPublishingJobs: PublishingJob[] = [
  {
    id: "pub1",
    deliverableId: "del_north_1",
    projectTitle: "Northwind — carousel B",
    channel: "meta_ads",
    status: "live",
    scheduledAt: iso("2026-04-08T08:00:00"),
    publishedAt: iso("2026-04-08T08:05:00"),
    metrics: { impressions: 128000, clicks: 4100, engagement: 0.048 },
  },
  {
    id: "pub2",
    deliverableId: "del_pulse_1",
    projectTitle: "Pulse — reels batch",
    channel: "instagram",
    status: "scheduled",
    scheduledAt: iso("2026-04-12T14:00:00"),
  },
]

export const demoChannelConfigs: ChannelConfig[] = [
  { channel: "meta_ads", label: "Meta Ads", connected: true, accountName: "AgencyOS — Main", lastSync: iso("2026-04-11T07:00:00") },
  { channel: "google_ads", label: "Google Ads", connected: true, accountName: "Search + PMax", lastSync: iso("2026-04-10T22:00:00") },
  { channel: "instagram", label: "Instagram", connected: true, accountName: "@agencyos.studio", lastSync: iso("2026-04-11T06:30:00") },
  { channel: "linkedin", label: "LinkedIn", connected: false },
  { channel: "twitter", label: "X / Twitter", connected: true, accountName: "@agencyos", lastSync: iso("2026-04-01") },
  { channel: "mailchimp", label: "Mailchimp", connected: true, accountName: "Lifecycle", lastSync: iso("2026-04-09") },
  { channel: "tiktok", label: "TikTok Ads", connected: false },
]

export const demoBenchmarks: Benchmark[] = [
  { id: "b1", category: "Creative", metric: "Avg. turnaround (days)", yourValue: 4.2, industryAvg: 9.1, topPerformer: 3.1, percentile: 88, trend: "up", unit: "d" },
  { id: "b2", category: "Quality", metric: "Client satisfaction", yourValue: 8.7, industryAvg: 7.9, topPerformer: 9.2, percentile: 82, trend: "stable", unit: "/10" },
  { id: "b3", category: "Economics", metric: "Gross margin", yourValue: 0.66, industryAvg: 0.42, topPerformer: 0.71, percentile: 91, trend: "up", unit: "%" },
]

export const demoSLATiers: SLATier[] = [
  { tier: "starter", firstDraftHours: 72, finalDeliveryHours: 240, revisionTurnaroundHours: 48, maxRevisions: 2, guaranteedCredits: 500, penaltyPercent: 5 },
  { tier: "professional", firstDraftHours: 48, finalDeliveryHours: 168, revisionTurnaroundHours: 24, maxRevisions: 4, guaranteedCredits: 2000, penaltyPercent: 10 },
  { tier: "enterprise", firstDraftHours: 24, finalDeliveryHours: 120, revisionTurnaroundHours: 12, maxRevisions: 8, guaranteedCredits: 10000, penaltyPercent: 15 },
]

export const demoSLACompliance: SLACompliance[] = [
  { id: "sla1", projectId: "proj_pulse", projectTitle: "Pulse Health — Q2 social motion kit", clientName: "Pulse Health", tier: "enterprise", metric: "First draft", targetHours: 24, actualHours: 19, status: "on_track", creditIssued: 0 },
  { id: "sla2", projectId: "proj_north", projectTitle: "Northwind — performance creative A/B", clientName: "Northwind Commerce", tier: "professional", metric: "Revision loop", targetHours: 24, actualHours: 26, status: "at_risk", creditIssued: 0 },
]

export const demoInvoices: Invoice[] = [
  {
    id: "inv1",
    tenantId: "t_demo",
    clientName: "Lumen Analytics",
    amount: 42000,
    status: "sent",
    items: [
      { description: "Retainer — creative ops (Apr)", quantity: 1, unitPrice: 35000, total: 35000 },
      { description: "Variable — generation overage", quantity: 1, unitPrice: 7000, total: 7000 },
    ],
    createdAt: iso("2026-04-01"),
    dueDate: iso("2026-04-15"),
  },
  {
    id: "inv2",
    tenantId: "t_demo",
    clientName: "Vertex Labs",
    amount: 5800,
    status: "paid",
    items: [{ description: "Collateral — investor one-pager + deck", quantity: 1, unitPrice: 5800, total: 5800 }],
    createdAt: iso("2026-03-28"),
    dueDate: iso("2026-04-10"),
    paidAt: iso("2026-04-04"),
  },
]

export const demoCreditPacks: CreditPack[] = [
  { id: "cp1", name: "Starter", credits: 500, price: 499, pricePerCredit: 1.0, popular: false, features: ["Email support", "Standard SLA"] },
  { id: "cp2", name: "Growth", credits: 2000, price: 1599, pricePerCredit: 0.8, popular: true, features: ["Priority routing", "Pro SLA", "Expert escalation"] },
  { id: "cp3", name: "Scale", credits: 10000, price: 6999, pricePerCredit: 0.7, popular: false, features: ["Dedicated CSM", "Enterprise SLA", "Custom integrations"] },
]

export const demoUsageRecords: UsageRecord[] = [
  { tenantId: "t_demo", month: "2026-04", projectsCompleted: 18, creditsUsed: 14200, creditsRemaining: 5800, totalSpend: 142000, aiCost: 48000, margin: 0.662 },
]

export const demoBrandProfiles: BrandProfile[] = [
  {
    id: "brand_lumen",
    tenantId: "t_demo",
    name: "Lumen Analytics",
    websiteUrl: "https://lumenanalytics.example",
    logoUrl: "https://placehold.co/200x80/4f46e5/ffffff/png?text=Lumen",
    colors: [
      { name: "Indigo", hex: "#4F46E5", usage: "primary" },
      { name: "Slate", hex: "#0F172A", usage: "neutral" },
      { name: "Sky", hex: "#38BDF8", usage: "accent" },
    ],
    fonts: [
      { name: "Inter", usage: "body", weight: "400–700" },
      { name: "Söhne", usage: "heading", weight: "600" },
    ],
    toneOfVoice: "Precise, optimistic, builder-friendly.",
    values: ["Trust", "Velocity", "Transparency"],
    targetAudience: "Data teams at growth-stage SaaS",
    industry: "B2B SaaS",
    competitors: ["Mixpanel", "Amplitude"],
    assets: [],
    dnaScore: 0.91,
    projectsCompleted: 6,
    lastUpdated: iso("2026-04-10"),
  },
  {
    id: "brand_pulse",
    tenantId: "t_demo",
    name: "Pulse Health",
    websiteUrl: "https://pulsehealth.example",
    logoUrl: "https://placehold.co/200x80/0ea5e9/ffffff/png?text=Pulse",
    colors: [
      { name: "Teal", hex: "#0D9488", usage: "primary" },
      { name: "Sand", hex: "#F8FAFC", usage: "neutral" },
    ],
    fonts: [{ name: "DM Sans", usage: "body", weight: "400–600" }],
    toneOfVoice: "Warm, clinical clarity without jargon.",
    values: ["Care", "Evidence", "Access"],
    targetAudience: "Health-conscious millennials",
    industry: "Health & wellness",
    competitors: ["Hims", "Ro"],
    assets: [],
    dnaScore: 0.87,
    projectsCompleted: 4,
    lastUpdated: iso("2026-04-08"),
  },
]

const activeProjects = demoProjects.filter((p) => p.status !== "delivered" && p.status !== "draft").length
const totalProjects = demoProjects.length
const latest = demoRevenueMetrics[demoRevenueMetrics.length - 1]
const prev = demoRevenueMetrics[demoRevenueMetrics.length - 2]

export const demoDashboardStats = {
  totalRevenue: demoRevenueMetrics.reduce((a, m) => a + m.revenue, 0),
  monthlyRevenue: latest.revenue,
  revenueGrowth: prev ? (latest.revenue - prev.revenue) / prev.revenue : 0.12,
  activeProjects,
  totalProjects,
  avgMargin: latest.margin,
  avgQualityScore: 8.5,
  avgTurnaround: 4.2,
  totalClients: 24,
  activeClients: latest.clients,
  pipelineValue: demoLeads.reduce((a, l) => a + l.value, 0),
  expertUtilization: 0.78,
  autonomousRate: 0.41,
  aiCostPerProject: Math.round(latest.cost / Math.max(latest.projects, 1)),
}
